[build-system]
requires = ["setuptools >= 61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where =["Lib"]

[project]
name = "notobuilder"
dynamic = ["version"]
description = "A build system for Noto fonts"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Simon Cozens", email = "simon@simon-cozens.org" },
]
dependencies = [
    "chevron==0.14.0",
    "sh>=2.2.4",
    "font-v",
]

[project.scripts]
notobuilder = "notobuilder.__main__:main"
